language: php
php:
  - 7.0.8
  - 7.1
services:
  - mysql
before_script:
  - travis_retry composer self-update
install:
  - cp app/config/parameters.yml.test app/config/parameters.yml
  - composer install --prefer-dist --no-interaction
  - mkdir _fix && cd _fix && echo '{}' > composer.json && composer require friendsofphp/php-cs-fixer
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - _fix/vendor/bin/php-cs-fixer fix -v --dry-run
after_success:
  - bash <(curl -s https://codecov.io/bash)

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache
