language: php
php:
  - 7.0
services:
  - mysql
before_script:
  - travis_retry composer self-update
install:
  - cp app/config/parameters.yml.test app/config/parameters.yml
  - composer install --prefer-dist --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/php-cs-fixer fix --dry-run
after_success:
  - bash <(curl -s https://codecov.io/bash)

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache
