#!/usr/bin/env php
<?php

if (is_file(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
}

if (is_file(__DIR__ . '/../autoload.php')) {
    require __DIR__ . '/../autoload.php';
}


use Kisphp\Core\CommandsCollector;
use Kisphp\Core\KisphpApplication;

$commandsCollector = new CommandsCollector();

$app = new KisphpApplication($commandsCollector);
$app->boot()->run();
