#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Kisphp\Core\CommandsCollector;
use Kisphp\Core\KisphpApplication;

$commandsCollector = new CommandsCollector();

$app = new KisphpApplication($commandsCollector);
$app->boot()->run();
