#!/usr/bin/env php
<?php

if (is_file($_SERVER['PWD'] . '/vendor/autoload.php')) {
    require $_SERVER['PWD'] . '/vendor/autoload.php';
}

if (is_file($_SERVER['PWD'] . '/../autoload.php')) {
    require $_SERVER['PWD'] . '/../autoload.php';
}

use Kisphp\Core\CommandsCollector;
use Kisphp\Core\KisphpApplication;

$commandsCollector = new CommandsCollector();

$app = new KisphpApplication($commandsCollector);
$app->boot()->run();
